F=

.PHONY: t
t: .db
	mix test ${F}

.PHONY:
db:
	rm -f .db
	$(MAKE) --no-print-directory .db

.db:
	cockroach sql --url "${CRDB_DSN}" -e "DROP TABLE IF EXISTS roachfeed_test"
	cockroach sql --url "${CRDB_DSN}" \
		-e "CREATE TABLE IF NOT EXISTS roachfeed_test (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name STRING)"
	cockroach sql --url "${CRDB_DSN}" -e "DROP TABLE IF EXISTS roachfeed_test"
	echo "generated by make" > .db
